# Generated by Django 5.2.4 on 2025-07-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
